---
- name: Install WireGuard and dependencies
  apt:
    name:
      - wireguard
      - iproute2
    state: present
  when: ansible_os_family == 'Debian'

- name: Stop WireGuard service if running
  systemd:
    name: wg-quick@wg0
    state: stopped
    enabled: no

- name: Remove existing WireGuard configuration
  file:
    path: /etc/wireguard/wg0.conf
    state: absent

- name: Ensure WireGuard directory exists
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Generate WireGuard private key
  command: wg genkey
  register: wg_private_key

- name: Generate WireGuard public key
  shell: "echo {{ wg_private_key.stdout }} | wg pubkey"
  register: wg_public_key

- name: Set WireGuard keys as variables
  set_fact:
    my_wg_private_key: "{{ wg_private_key.stdout }}"
    my_wg_public_key: "{{ wg_public_key.stdout }}"

- name: Set peer_wg_public_key dynamically
  set_fact:
    peer_wg_public_key: "{{ hostvars[peer].wg_public_key.stdout }}"
  vars:
    peer: "{{ 'client' if inventory_hostname == 'server' else 'server' }}"

- name: Configure WireGuard interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Deploy VXLAN setup script
  template:
    src: vxlan.sh.j2
    dest: /usr/local/sbin/vxlan.sh
    owner: root
    group: root
    mode: '0755'

- name: Run VXLAN setup script
  command: bash /usr/local/sbin/vxlan.sh

- name: Enable IP forwarding

  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Install UFW
  apt:
    name: ufw
    state: present
  when: ansible_os_family == 'Debian'

- name: Allow VXLAN UDP 4789 only from WireGuard peer
  ufw:
    rule: allow
    port: 4789
    proto: udp
    from_ip: '{{ peer_wg_private_ip }}'
  when: ansible_os_family == 'Debian'

- name: Deny VXLAN UDP 4789 from others
  ufw:
    rule: deny
    port: 4789
    proto: udp
    from_ip: 'any'
  when: ansible_os_family == 'Debian'

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow
  when: ansible_os_family == 'Debian'


- name: Install netcat-openbsd as an alternative
  apt:
    name: netcat-openbsd
    state: present
  when: ansible_os_family == 'Debian'

- name: Check VXLAN port connectivity to peer
  command: nc -zvu {{ peer_wg_private_ip }} 4789
  register: nc_vxlan_result
  ignore_errors: yes

- name: Display VXLAN port connectivity result
  debug:
    msg: "VXLAN port connectivity to {{ peer_wg_private_ip }}: {{ nc_vxlan_result.stdout }}"